version: 1
disable_existing_loggers: false
formatters:
  simple:
    format: '%(asctime)s [t%(thread)d] %(name)s - %(levelname)s : %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: simple
    level: DEBUG
    filename: ../../logs/app.log
    atTime: 17:01
    when: D
    interval: 1
    backupCount: 7

loggers:
  simpleExample:
    level: DEBUG
    handlers: [file, console]
    propagate: no
root:
  level: INFO
  handlers: [file, console]